### ISSUE TITLE
El email no existe

### ISSUE THREAD

**Issue by Madh93** [axelhzf/treexor-code-challenge-tlp2k16#1]
Buenas.

La dirección de correo electrónico del concurso no existe a día de hoy.

Saludos :smile:

**Comment by axelhzf** [comment]
Ops, hubo un problema técnico con el alias del email :(

Puedes intentarlo de nuevo a ver si está arreglado?
Si te sigue dando error envía el correo a kiko@treexor.com

**Comment by Madh93** [comment]
Si, parece que ya funciona :+1:
